apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bombardier
  name: bombardier-ns-95
  namespace: ns-95
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bombardier
  template:
    metadata:
      labels:
        app: bombardier
    spec:
      containers:
      - name: bombardier
        image: alpine/bombardier:v1.2.5
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        # guaranteed qos
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 50Mi
        args: ["-c", "sleep 5 && for run in $(seq 1 100000); do bombardier -c 10 -d 10s -r 15 -p i,p,r http://tier-1-app-a.ns-95.svc.cluster.local:8080; done"]