apiVersion: v1
kind: ServiceAccount
metadata:
  name: vegeta
  namespace: ns-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vegeta
  name: vegeta-ns-1
  namespace: ns-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegeta
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      serviceAccountName: vegeta
      containers:
      - name: vegeta
        image: ably77/vegeta:0.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        # guaranteed qos
        resources:
          requests:
            cpu: 500m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 300Mi
        env:
        - name: HOSTNAME
          value: 34.125.231.145
        - name: PREFIX_PATH
          value: ns-1
        - name: REQUESTS_PER_SECOND
          value: "600"
        - name: DURATION
          value: "10s"
        args: 
          - "-c"
          - 'sleep 5; for run in $(seq 1 100000); do echo "GET http://${HOSTNAME}/${PREFIX_PATH}" | vegeta attack -dns-ttl=0 -keepalive -http2=true -rate ${REQUESTS_PER_SECOND}/1s -duration=${DURATION} | tee results.bin | vegeta report -type=text; done'
