# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- vegeta-ns-1.yaml
- vegeta-ns-2.yaml
- vegeta-ns-3.yaml
- vegeta-ns-4.yaml
- vegeta-ns-5.yaml
- vegeta-ns-6.yaml
- vegeta-ns-7.yaml
- vegeta-ns-8.yaml
- vegeta-ns-9.yaml
- vegeta-ns-10.yaml
- vegeta-ns-11.yaml
- vegeta-ns-12.yaml
- vegeta-ns-13.yaml
- vegeta-ns-14.yaml
- vegeta-ns-15.yaml
- vegeta-ns-16.yaml
- vegeta-ns-17.yaml
- vegeta-ns-18.yaml
- vegeta-ns-19.yaml
- vegeta-ns-20.yaml
- vegeta-ns-21.yaml
- vegeta-ns-22.yaml
- vegeta-ns-23.yaml
- vegeta-ns-24.yaml
- vegeta-ns-25.yaml
- vegeta-ns-26.yaml
- vegeta-ns-27.yaml
- vegeta-ns-28.yaml
- vegeta-ns-29.yaml
- vegeta-ns-30.yaml
- vegeta-ns-31.yaml
- vegeta-ns-32.yaml
- vegeta-ns-33.yaml
- vegeta-ns-34.yaml
- vegeta-ns-35.yaml
- vegeta-ns-36.yaml
- vegeta-ns-37.yaml
- vegeta-ns-38.yaml
- vegeta-ns-39.yaml
- vegeta-ns-40.yaml
- vegeta-ns-41.yaml
- vegeta-ns-42.yaml
- vegeta-ns-43.yaml
- vegeta-ns-44.yaml
- vegeta-ns-45.yaml
- vegeta-ns-46.yaml
- vegeta-ns-47.yaml
- vegeta-ns-48.yaml
- vegeta-ns-49.yaml
- vegeta-ns-50.yaml
- vegeta-ns-51.yaml
- vegeta-ns-52.yaml
- vegeta-ns-53.yaml
- vegeta-ns-54.yaml
- vegeta-ns-55.yaml
- vegeta-ns-56.yaml
- vegeta-ns-57.yaml
- vegeta-ns-58.yaml
- vegeta-ns-59.yaml
- vegeta-ns-60.yaml
- vegeta-ns-61.yaml
- vegeta-ns-62.yaml
- vegeta-ns-63.yaml
- vegeta-ns-64.yaml
- vegeta-ns-65.yaml
- vegeta-ns-66.yaml
- vegeta-ns-67.yaml
- vegeta-ns-68.yaml
- vegeta-ns-69.yaml
- vegeta-ns-70.yaml
- vegeta-ns-71.yaml
- vegeta-ns-72.yaml
- vegeta-ns-73.yaml
- vegeta-ns-74.yaml
- vegeta-ns-75.yaml
- vegeta-ns-76.yaml
- vegeta-ns-77.yaml
- vegeta-ns-78.yaml
- vegeta-ns-79.yaml
- vegeta-ns-80.yaml
- vegeta-ns-81.yaml
- vegeta-ns-82.yaml
- vegeta-ns-83.yaml
- vegeta-ns-84.yaml
- vegeta-ns-85.yaml
- vegeta-ns-86.yaml
- vegeta-ns-87.yaml
- vegeta-ns-88.yaml
- vegeta-ns-89.yaml
- vegeta-ns-90.yaml
- vegeta-ns-91.yaml
- vegeta-ns-92.yaml
- vegeta-ns-93.yaml
- vegeta-ns-94.yaml
- vegeta-ns-95.yaml
- vegeta-ns-96.yaml
- vegeta-ns-97.yaml
- vegeta-ns-98.yaml
- vegeta-ns-99.yaml
- vegeta-ns-100.yaml





# patch nodeSelector and tolerations on all Deployments
patches:
- patch: |-
    kind: not-important
    metadata:
      name: not-important
    spec:
      template:
        spec:
          nodeSelector:
            node: loadgen
          tolerations:
          - key: cloud.google.com/node
            operator: Equal
            value: "loadgen"
            effect: NoSchedule
  target:
    kind: Deployment