apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "tier2a"
spec:
  endpointSelector:
    matchLabels:
      app: tier-2-app-a
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: tier-1-app-a
    authentication:
      mode: "required"
    toPorts:
    - ports:
      - port: '8080'
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/"
