apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "tier1"
spec:
  endpointSelector:
    matchLabels:
      app: tier-1-app-a
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: vegeta
    authentication:
      mode: "required"
    toPorts:
    - ports:
      - port: '8080'
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/"
